version: 0.0
os: linux

files:
  - source: ./build/libs/ROOT.war
    destination: /var/lib/tomcat8/webapps

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: centos
  #ValidateService:
   #- location: ./validateService.sh
    # timeout: 180
     #runas: centos

  